stages:
  - deploy

#before_script:
#  - bash
#  - eval `ssh-agent -s`
#  - mkdir -p ~/.ssh
#  - ssh-add <(echo "$SERIALBOX_SSH_KEY") 2>/dev/null
#  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#  - apt-get install -y git
#  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
#  - pip install -r ./requirements/base.txt
#  - pip install -r ./requirements/production.txt

# TODO- add unit tests

deploy:
    stage: deploy
    image: docker:latest
    services:
    - docker:dind
    script:
    - pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker-compose -f local.yml build
    - docker-compose down
    - docker-compose up -d --force-recreate
    environment: production
