stages:
  - test-python
  - build-docs

python3_6_unit_test:
  image: seriallab/python3.6dev
  stage: test-python
  script:
  - apt-get install -y git
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install -r ./requirements/test.txt
  - export TESTING=True
  - coverage run manage.py test --settings=config.settings.test
  - coverage report -m
  - coverage html
  artifacts:
    paths:
      - htmlcov/


pages:
  image: seriallab/python3.6dev
  stage: build-docs
  script:
  - apt-get install -y git
  - export PYTHONPATH=$PYTHONPATH:$CI_PROJECT_DIR
  - pip install -r ./requirements/test.txt
  - pip install sphinx sphinx_rtd_theme pygments ipython recommonmark
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
      paths:
      - public
      expire_in: 1d
  only:
    - tags
