version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.celery
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    image: postgres
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:3-management

  celeryworker:
    <<: *django
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    env_file:
      - ./.envs/.local/.celery
    ports:
      - "5555:5555"
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    env_file:
      - ./.envs/.local/.celery
    ports:
      - "5556:5556"
    command: /start-celerybeat.sh
