version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}
  media:
  static:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    env_file: ./.envs/.production/.django
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  rabbitmq:
    image: rabbitmq:3-management

  celeryworker:
    <<: *django
    depends_on:
     - postgres
     - rabbitmq
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - rabbitmq
    command: /start-celerybeat.sh

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
      - celerybeat
      - celeryworker
    volumes_from:
      - django
    ports:
      - "0.0.0.0:80:80"
