version: '2.4'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file: ./.envs/.production/.django
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_backup:/backups
    env_file:
      - ./.envs/.production/.postgres

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  celeryworker:
    <<: *django
    depends_on:
     - postgres
     - rabbitmq
    command: /start-celeryworker.sh

# ********************** OPTIONAL
# Uncomment this section along with the section in NGINX if you need to
# implement any celery beat functionality with QU4RTET.
#  celerybeat:
#    <<: *django
#    depends_on:
#      - postgres
#      - rabbitmq
#    command: /start-celerybeat.sh
# **********************

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
      #- celerybeat -- see notes above in the commented out beat section.
      - celeryworker
    volumes:
      - ./staticfiles:/static
      - ./media:/media
    ports:
      - "0.0.0.0:80:80"

